name: employee-salary-manager

services:

  frontend:
    container_name: frontend
    depends_on:
      - database
      - pgadmin
    build:
      dockerfile: packages/web/frontend/Dockerfile
      context: .
    develop:
      watch:
        - action: sync
          path: packages/web/frontend
          target: /app/packages/web/frontend
          ignore:
            - node_modules
        - action: sync
          path: packages/core
          target: /app/packages/core
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    ports:
      - "4321:4321"
    volumes:
      - /app/node_modules
    entrypoint: >
      sh -c "
        until nc -z database 5432; do
          echo 'â³ Waiting for databaseâ€¦';
          sleep 1;
        done;
        echo 'âœ… Database up â€” pulling any changes';
        yarn db:pull;
        echo 'ğŸ› ï¸ Pull complete â€” generating client';
        yarn db:generate;
        echo 'ğŸš€ Starting Next.jsâ€¦';
        yarn frontend:dev
      "

  database:
    container_name: database
    image: 'postgres:17.4'
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/
      - ./packages/database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4:9.3
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - admin-db:/var/lib/pgadmin/
      - ./packages/database/servers.json:/pgadmin4/servers.json

volumes:
  db:
    driver: local
  admin-db:
    driver: local
    